### GET request to example server
POST 127.0.0.1/api/user/public/login2
Content-Type: application/json

{
  "login": "admin",
  "password": "1234"
}
###
GET 127.0.0.1/api/user/public/login/admin/13234